[[redirects]]
  from = "/school"
  to = "/school.html"
  status = 200

[[redirects]]
  from = "/school/*"
  to = "/school.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
